add_subdirectory(kvantum)
add_subdirectory(xdg)
add_subdirectory(smod-theme)
install(FILES ${CMAKE_SOURCE_DIR}/misc/branding/kcminfo.png DESTINATION ${CMAKE_INSTALL_PREFIX}/share/vistathemeplasma/branding)
install(FILES ${CMAKE_SOURCE_DIR}/misc/reflection.png DESTINATION ${CMAKE_INSTALL_PREFIX}/share/vistathemeplasma/)
install(FILES ${CMAKE_SOURCE_DIR}/misc/fallback-picture.png DESTINATION ${CMAKE_INSTALL_PREFIX}/share/vistathemeplasma/)
